# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import rpc.authenticator_server.types.authenticator_pb2 as authenticator__pb2


class AuthenticatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckToken = channel.unary_unary(
                '/authenticator.Authenticator/CheckToken',
                request_serializer=authenticator__pb2.Token.SerializeToString,
                response_deserializer=authenticator__pb2.TokenValidity.FromString,
                )
        self.GetUserID = channel.unary_unary(
                '/authenticator.Authenticator/GetUserID',
                request_serializer=authenticator__pb2.Token.SerializeToString,
                response_deserializer=authenticator__pb2.UserID.FromString,
                )


class AuthenticatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckToken,
                    request_deserializer=authenticator__pb2.Token.FromString,
                    response_serializer=authenticator__pb2.TokenValidity.SerializeToString,
            ),
            'GetUserID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserID,
                    request_deserializer=authenticator__pb2.Token.FromString,
                    response_serializer=authenticator__pb2.UserID.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authenticator.Authenticator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Authenticator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authenticator.Authenticator/CheckToken',
            authenticator__pb2.Token.SerializeToString,
            authenticator__pb2.TokenValidity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authenticator.Authenticator/GetUserID',
            authenticator__pb2.Token.SerializeToString,
            authenticator__pb2.UserID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
