# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authenticator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61uthenticator.proto\x12\rauthenticator\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\rTokenValidity\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\"\x19\n\x06UserID\x12\x0f\n\x07user_id\x18\x01 \x01(\t2\x8f\x01\n\rAuthenticator\x12\x42\n\nCheckToken\x12\x14.authenticator.Token\x1a\x1c.authenticator.TokenValidity\"\x00\x12:\n\tGetUserID\x12\x14.authenticator.Token\x1a\x15.authenticator.UserID\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authenticator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOKEN']._serialized_start=38
  _globals['_TOKEN']._serialized_end=60
  _globals['_TOKENVALIDITY']._serialized_start=62
  _globals['_TOKENVALIDITY']._serialized_end=95
  _globals['_USERID']._serialized_start=97
  _globals['_USERID']._serialized_end=122
  _globals['_AUTHENTICATOR']._serialized_start=125
  _globals['_AUTHENTICATOR']._serialized_end=268
# @@protoc_insertion_point(module_scope)
